### PR TITLE
8268591: a few runtime/jni tests don't need `/othervm`

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

could you please review this small and trivial patch that removes `/othervm` from 3 `runtime/jni` tests?
from JBS:
> `runtime/jni/registerNativesWarning/TestRegisterNativesWarning.java`, `checked/TestCheckedEnsureLocalCapacity.java`, and `atExit/TestAtExit.java` use `main/othervm` whereas in fact, they don't need `othervm`, and if we had CODETOOLS-7902658 implemented, they would have used `driver` mode. this RFE is to remove `/othervm`, so we at least won't waste time on creating a fresh JVM.

the patch explicitly sets `-Djava.library.path=` for the child processes so they are able to locate native libraries.

testing: `runtime/jni` on `{linux,windows,macosx}-x64`

Thanks,
-- Igor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268591](https://bugs.openjdk.java.net/browse/JDK-8268591): a few runtime/jni tests don't need `/othervm`

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Mikhailo Seledtsov](https://openjdk.java.net/census#mseledtsov) (@mseledts - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/18/head:pull/18` \
`$ git checkout pull/18`

Update a local copy of the PR: \
`$ git checkout pull/18` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/18/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18`

View PR using the GUI difftool: \
`$ git pr show -t 18`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/18.diff">https://git.openjdk.java.net/jdk17/pull/18.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
Hi Igor,

The test classes, run by jtreg, load native libraries (though they could possibly be refactored so that is not necessary) so I would expect we would want othervm here because we do not want to load multiple unrelated libraries in the shared VM implied by "main".

I also don't understand why you now need to set java.library.path explicitly in some of the tests ??

Thanks,
David

**Comment by iignatev** [comment]
> The test classes, run by jtreg, load native libraries (though they could possibly be refactored so that is not necessary) so I would expect we would want othervm here because we do not want to load multiple unrelated libraries in the shared VM implied by "main".

`jtreg` uses a separate classloader for each test, and native libraries are to be unloaded when CL is GC'ed, so there should be no unrelated libraries in shared VMs.

> I also don't understand why you now need to set java.library.path explicitly in some of the tests ??

frankly, I don't fully understand why it's needed, but these tests started to fail w/ `UnsatisfiedLinkError` when I removed `/othervm` and setting `java.library.path` fixed the problem. I assumed it's because we don't set/propagate `LD_LIBRARY_PATH` (or its equivalent), yet all my attempts to reproduce this behavior and the problem w/ a small test case failed, I'll dig deeper next week.

Thanks,
-- Igor

**Review by dholmes-ora — APPROVED** [review]
Thanks for the explanations Igor.

David

**Review by mseledts — APPROVED** [review]
Looks reasonable to me.

**Comment by iignatev** [comment]
David, Misha, thank you for your reviewes!

/integrate

**Pull request closed without merging**
