### PR TITLE
8260194: Update the documentation for -Xcheck:jni 

### PR DESCRIPTION
**Pull request by dholmes-ora**
Please review this update to the -Xcheck:jni description in the java manpage.

For ease of reading there was a temporary commit of the generated java.html page. This can be viewed here:

https://htmlpreview.github.io/?https://github.com/openjdk/jdk17/blob/4f336dd3985b654dc3fbacabdcfccf590ea918e5/java.html

A preemptive note on the punctuation of the lists. The  first and second level level list items are all complete sentences and so end with a period. The third level list items are phrases, not full sentences and so do not end with a period. :)

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260194](https://bugs.openjdk.java.net/browse/JDK-8260194): Update the documentation for -Xcheck:jni

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to 7031dc970bd46f82e6aa247ca8b1ffd02c2e4a67
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/52/head:pull/52` \
`$ git checkout pull/52`

Update a local copy of the PR: \
`$ git checkout pull/52` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/52/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 52`

View PR using the GUI difftool: \
`$ git pr show -t 52`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/52.diff">https://git.openjdk.java.net/jdk17/pull/52.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Looks good.  Just a question:

"A jFieldID, or jMethodID, is detected as being invalid. For example:"

Is this the casing of these used in JNI?

**Comment by dholmes-ora** [comment]
Thanks for the review Coleen!

Good catch on the incorrect case for jfieldID and jmethodID - now fixed.

David

**Comment by dholmes-ora** [comment]
Thanks for the review Harold!

**Pull request closed without merging**
