### PR TITLE
8268672: C2: assert(!loop->is_member(u_loop)) failed: can be in outer loop or out of both loops only

### PR DESCRIPTION
**Pull request by rwestrel**
This is caused by the fix for 8263303 in which I changed the code of
loop cloning of a strip mined loop so nodes that are pinned in the
outer loop but not referenced by the loop's safepoint are moved out of
the loop before cloning:

https://github.com/openjdk/jdk/commit/d4377afb999f4f03d384ded97771c83ea1c1f513#diff-7b82624b78127158abbce6835eeba196bd062aee59512ec2d4e4c8c7d681573bR1980

The assert failure here is caused by a node that has its control input
set to the inner loop but is assigned control by PhaseIdealLoop out of
the inner loop. The assert fires because the change from 8263303
affects the condition that the assert checks. I still think, in
principle, the fix from 8263303 is the good one so I propose to simply
reorganize the change from 8263303 so the assert doesn't wrongly fire.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268672](https://bugs.openjdk.java.net/browse/JDK-8268672): C2: assert(!loop->is_member(u_loop)) failed: can be in outer loop or out of both loops only

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/88/head:pull/88` \
`$ git checkout pull/88`

Update a local copy of the PR: \
`$ git checkout pull/88` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/88/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 88`

View PR using the GUI difftool: \
`$ git pr show -t 88`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/88.diff">https://git.openjdk.java.net/jdk17/pull/88.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Looks good.

**Review by neliasso — APPROVED** [review]
Looks good!

**Comment by rwestrel** [comment]
@vnkozlov @neliasso thanks for the reviews

**Pull request closed without merging**
