### PR TITLE
8269746: C2: assert(!in->is_CFG()) failed: CFG Node with no controlling input?

### PR DESCRIPTION
**Pull request by rwestrel**
The backedge and the exit test of an inner strip mined loop are
removed. A safepoint is right above the inner loop exit test when that
happens. The outer strip mined loop safepoint is then processed by
igvn which finds the other safepoint. This causes the outer loop
safepoint to be replaced by the safepoint that was in the inner
loop. Then the outer loop back edge is removed by igvn. This is done
by replacing the loop exit by the control of the outer loop
safepoint. Given the outer loop safepoint was replaced by a dominating
safepoint, that logic replaces the oiter loop exit with the dominating
safepoint control input. That must be harmless most of the time, but
in this particular case a Store was between the 2 safepoints. That
Store is still reachable in the graph but its control is not.

Note: test case not included because the crash no longer reproduces (supposedly because order of node processing by igvn matters)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269746](https://bugs.openjdk.java.net/browse/JDK-8269746): C2: assert(!in->is_CFG()) failed: CFG Node with no controlling input?

### Reviewers
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/222/head:pull/222` \
`$ git checkout pull/222`

Update a local copy of the PR: \
`$ git checkout pull/222` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/222/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 222`

View PR using the GUI difftool: \
`$ git pr show -t 222`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/222.diff">https://git.openjdk.java.net/jdk17/pull/222.diff</a>

</details>

### CODE REVIEW

**Review by chhagedorn — APPROVED** [review]
Looks good!

Have you tried playing around with `-XX:+StressIGVN` to trigger it again?

**Comment by rwestrel** [comment]
> Have you tried playing around with `-XX:+StressIGVN` to trigger it again?

Thanks for the suggestion. I tried running the test case 1000 times in a loop with -XX:+StressIGVN but the crash doesn't reproduce.

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable to me.

**Comment by chhagedorn** [comment]
> > Have you tried playing around with `-XX:+StressIGVN` to trigger it again?
> 
> Thanks for the suggestion. I tried running the test case 1000 times in a loop with -XX:+StressIGVN but the crash doesn't reproduce.

Okay, thanks for trying it!

**Comment by rwestrel** [comment]
@TobiHartmann @chhagedorn thanks for the reviews

**Pull request closed without merging**
