### PR TITLE
8268265:  MutableSpaceUsedHelper::take_sample() hits assert(left >= right) failed: avoid overflow

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to PerfData-based heap usage reporting by SerialGC
and ParallelGC.

For both of these collectors, the periodic heap usage sampling and reporting
by the Watcher thread involves sampling the difference between each space's
current allocation pointer and its base pointer.  But the Watcher thread
runs during GC safepoints, which means that sampling may occasionally occur
while the GC is in the process of updating the space being sampled.  This
can result in a sample with a bogus value or even an assertion failure after
JDK-8260046.

Other collectors seem to avoid this by sampling and recording the heap usage
value at specific synchronous times rather than asynchronously by the
Watcher thread.

There isn't a particularly good place for synchronous updates for ParallelGC
and SerialGC, so this change doesn't do so.  Instead, it makes the existing
asynchronous updates safe from interference by an in-progress GC.  This is
done by having the update done under the Heap_lock.  Introducing a more
fine-grained lock has the same problem as doing synchronous updates.  Rather
than possibly blocking the sampling Watcher thread for the duration of a GC,
it tries to lock the Heap_lock and skips sampling if it's not available.

Testing:
mach5 tier1-3, 5, 7 (3,5,7 are where focused Serial and ParallelGC testing is done).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268265](https://bugs.openjdk.java.net/browse/JDK-8268265): MutableSpaceUsedHelper::take_sample() hits assert(left >= right) failed: avoid overflow

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to a04516e8d2ca3a37e10b725320efa6d89c943217
 * [Ivan Walulya](https://openjdk.java.net/census#iwalulya) (@walulyai - Committer) ⚠️ Review applies to a04516e8d2ca3a37e10b725320efa6d89c943217

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/65/head:pull/65` \
`$ git checkout pull/65`

Update a local copy of the PR: \
`$ git checkout pull/65` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/65/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 65`

View PR using the GUI difftool: \
`$ git pr show -t 65`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/65.diff">https://git.openjdk.java.net/jdk17/pull/65.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Review by walulyai — APPROVED** [review]
lgtm!

**Comment by kimbarrett** [comment]
Thansk @tschatzl and @walulyai for reviews.

**Pull request closed without merging**
