### PR TITLE
8268576: jdk/jfr/event/gc/collection/TestSystemGc.java fails

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

jdk/jfr/event/gc/collection/TestSystemGc.java fails in jdk17 and jdk.

It can be fixed by renaming :
test/jdk/jdk/jfr/event/gc/collection/TestSystemGc.java -> test/jdk/jdk/jfr/event/gc/collection/TestSystemGC.java

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268576](https://bugs.openjdk.java.net/browse/JDK-8268576): jdk/jfr/event/gc/collection/TestSystemGc.java fails

### Reviewers
 * [Erik Gahlin](https://openjdk.java.net/census#egahlin) (@egahlin - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/11/head:pull/11` \
`$ git checkout pull/11`

Update a local copy of the PR: \
`$ git checkout pull/11` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/11/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11`

View PR using the GUI difftool: \
`$ git pr show -t 11`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/11.diff">https://git.openjdk.java.net/jdk17/pull/11.diff</a>

</details>

### CODE REVIEW

**Review by egahlin — APPROVED** [review]

**Comment by DamonFool** [comment]
Thanks @egahlin for your review.

Do you think it's trivial and can be pushed right now? @egahlin 
Thanks.

**Review by dholmes-ora — APPROVED** [review]
Thanks for fixing Jie!

David

**Comment by DamonFool** [comment]
> Thanks for fixing Jie!
> 
> David

Thanks @dholmes-ora .
Will push it soon.

**Comment by dholmes-ora** [comment]
Note this will fix the problem in JDK 18 not JDK 17. If you push to 18 you will need a manual backport to 17. If you push to 17 it will be automatically forweard-ported to 18.

**Comment by DamonFool** [comment]
> Note this will fix the problem in JDK 18 not JDK 17. If you push to 18 you will need a manual backport to 17. If you push to 17 it will be automatically forweard-ported to 18.

This PR is in JDK17.
So I think it should go into JDK 17, right?

**Comment by dholmes-ora** [comment]
Right. Sorry I didn't see the "17" only the openjdk:master :)

**Pull request closed without merging**
