### PR TITLE
8262017: C2: assert(n != __null) failed: Bad immediate dominator info.

### PR DESCRIPTION
**Pull request by chhagedorn**
This was already reviewed:

https://github.com/openjdk/jdk/pull/4362

but needs to be fixed in 17.

Thanks,
Christian

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262017](https://bugs.openjdk.java.net/browse/JDK-8262017): C2: assert(n != __null) failed: Bad immediate dominator info.

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Nils Eliasson](https://openjdk.java.net/census#neliasso) (@neliasso - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/192/head:pull/192` \
`$ git checkout pull/192`

Update a local copy of the PR: \
`$ git checkout pull/192` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/192/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 192`

View PR using the GUI difftool: \
`$ git pr show -t 192`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/192.diff">https://git.openjdk.java.net/jdk17/pull/192.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good.

**Review by neliasso — APPROVED** [review]
Looks good.

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by chhagedorn** [comment]
Thanks @rwestrel, @vnkozlov and @neliasso for your reviews!

**Pull request closed without merging**
