### PR TITLE
8267752: KVHashtable doesn't deallocate entries

### PR DESCRIPTION
**Pull request by navyxliu**
Add a free_entry iteration to the destructor of ~KVHashtables.
Tested with tier1-3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8267752](https://bugs.openjdk.java.net/browse/JDK-8267752): KVHashtable doesn't deallocate entries

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/110/head:pull/110` \
`$ git checkout pull/110`

Update a local copy of the PR: \
`$ git checkout pull/110` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/110/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 110`

View PR using the GUI difftool: \
`$ git pr show -t 110`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/110.diff">https://git.openjdk.java.net/jdk17/pull/110.diff</a>

</details>

### CODE REVIEW

**Comment by navyxliu** [comment]
hi, @coleenp 

[JDK-8269064](https://bugs.openjdk.java.net/browse/JDK-8269064) depends on this [JDK-8267752](https://bugs.openjdk.java.net/browse/JDK-8267752).  I think JDK-8267752 itself is also worthy in jdk17. 

ctx:
https://github.com/openjdk/jdk/pull/4537#event-4918066602 

Could you take a look at it?

**Comment by dholmes-ora** [comment]
As a P4 bug this is not permitted in JDK 17 under RDP1. You would need to change to a P3 with suitable justification.

**Comment by navyxliu** [comment]
I have consulted Coleen on JBS if there's any risk to bring her patch to jdk17. 
Meanwhile, I split JDK-8269064 into the urgent(https://github.com/openjdk/jdk17/pull/121) one and not so urgent one.  The later depends on this PR.

**Comment by navyxliu** [comment]
Close this PR because JDK-8267752 is P4, which doesn't  fit for the RDP1.

**Pull request closed without merging**
