### PR TITLE
8268768: idea.sh has been updated in surprising and incompatible ways

### PR DESCRIPTION
**Pull request by mcimadamore**
As the title says (please also refer to the JBS issue which describes all the issues in more details), the IDE support for IntelliJ has been updated with many enhancements as part of a seemingly innocuous "path handling" fix. The IDE doesn't appear to be usable in the same way it was in the past and many functionalities have been broken as a result (including support for jtreg test execution using the plugin).

For the above reasons, I'm reverting the plugin and idea.sh code to last known working version. Any targeted fix can be re-applied after the revert. Larger enhancements need to be discussed in the proper venue:

https://openjdk.java.net/groups/ide-support/

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268768](https://bugs.openjdk.java.net/browse/JDK-8268768): idea.sh has been updated in surprising and incompatible ways

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/61/head:pull/61` \
`$ git checkout pull/61`

Update a local copy of the PR: \
`$ git checkout pull/61` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/61/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 61`

View PR using the GUI difftool: \
`$ git pr show -t 61`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/61.diff">https://git.openjdk.java.net/jdk17/pull/61.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]
I think reverting this is fine. In the original review, I tried to point out that it needed to be looked at by people who actually use this functionality, but that never happened.

I wasn't aware of the ide-support mailing list. Would you like me to add automatic filtering in Skara so that changes touching these files are automatically labelled and mailed to that list?

**Comment by erikj79** [comment]
Exactly, I need to add the label and the mailing list config.

**Comment by erikj79** [comment]
Making the change here https://github.com/openjdk/skara/pull/1189

**Comment by erikj79** [comment]
This comment should now end up in ide-support-dev as well.

**Comment by mcimadamore** [comment]
> This comment should now end up in ide-support-dev as well.

Not really (at least for now) :-)

**Comment by erikj79** [comment]
It got stuck in moderation. Tim has fixed the config now, so this message should hopefully appear.

**Comment by mcimadamore** [comment]
> It got stuck in moderation. Tim has fixed the config now, so this message should hopefully appear.

Yep - I see emails now. Thanks this is really useful!

**Pull request closed without merging**
