### PR TITLE
8267399: C2: java/text/Normalizer/ConformanceTest.java test failed with assertion

### PR DESCRIPTION
**Pull request by rwestrel**
Already reviewed under https://github.com/openjdk/jdk/pull/4388

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267399](https://bugs.openjdk.java.net/browse/JDK-8267399): C2: java/text/Normalizer/ConformanceTest.java test failed with assertion

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * neliasso - **Reviewer** ⚠️ Added manually

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/109/head:pull/109` \
`$ git checkout pull/109`

Update a local copy of the PR: \
`$ git checkout pull/109` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/109/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 109`

View PR using the GUI difftool: \
`$ git pr show -t 109`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/109.diff">https://git.openjdk.java.net/jdk17/pull/109.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good. We have to re-approve when PR is moved it to JDK 17.

**Comment by rwestrel** [comment]
@vnkozlov thanks for re-reviewing

**Pull request closed without merging**
