### PR TITLE
8268884: C2: Compile::remove_speculative_types must iterate top-down

### PR DESCRIPTION
**Pull request by neliasso**
Hi,

The test fails on "assert(t->meet(t0) == t) failed: Not monotonic" in PhaseCCP for a CheckCastPPNode. The test is really simple. The CheckCastPP is hanging of the ParmNode for the 'this' pointer. The user of this is a call, with an infinite empty loop, that gets inlined. The loop will have a safepoint that keeps the JVM State - the CheckCastPP is kept alive by that SafePointNode.

The assert triggers because the type for the CheckCastPP has a speculative part. In the assert "assert(t->meet(t0) == t) failed: Not monotonic" - t is the type evaluated for the CheckCastPP, t0 is the previous type (from _types map), which has not been updated yet and is still Type::Top. 

t->meet(t0) will drop the speculative part and fail the comparison.

Suggested fix - change meet to meet_specualtive that will keep the speculative part.

Please review,
Best regards,
Nils Eliasson

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268884](https://bugs.openjdk.java.net/browse/JDK-8268884): C2: Compile::remove_speculative_types must iterate top-down

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**) ⚠️ Review applies to eaa80ffac0c28b18e640adf769f79d80c13aa8c4
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/170/head:pull/170` \
`$ git checkout pull/170`

Update a local copy of the PR: \
`$ git checkout pull/170` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/170/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 170`

View PR using the GUI difftool: \
`$ git pr show -t 170`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/170.diff">https://git.openjdk.java.net/jdk17/pull/170.diff</a>

</details>

### CODE REVIEW

**Comment by rwestrel** [comment]
Compile::remove_speculative_types() removes speculative types before CCP. How come this node still has a speculative type?

**Comment by neliasso** [comment]
> Hi Nils,
> Compile::remove_speculative_types() removes speculative types before CCP. How come this node still has a speculative type?

Compile::remove_speculative_types() traverses the graph bottom up. The checkcast is part of an infinite loop with no exit edge. It can't be reached from below.

**Comment by rwestrel** [comment]
> > Hi Nils,
> > Compile::remove_speculative_types() removes speculative types before CCP. How come this node still has a speculative type?
> 
> Compile::remove_speculative_types() traverses the graph bottom up. The checkcast is part of an infinite loop with no exit edge. It can't be reached from below.

Wouldn't it make sense then to improve Compile::remove_speculative_types() so we're guaranteed it removes all of them?

**Comment by neliasso** [comment]
> > > Hi Nils,
> > > Compile::remove_speculative_types() removes speculative types before CCP. How come this node still has a speculative type?
> > 
> > 
> > Compile::remove_speculative_types() traverses the graph bottom up. The checkcast is part of an infinite loop with no exit edge. It can't be reached from below.
> 
> Wouldn't it make sense then to improve Compile::remove_speculative_types() so we're guaranteed it removes all of them?

Absolutely. My first fix didn't take into account that the speculative types should have been removed.

**Comment by neliasso** [comment]
The new suggested fix changes so that Compile::remove_speculative_types() iterates the nodes from top to bottom. With this change all nodes that are reachable from the top will be visited.

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Review by vnkozlov — CHANGES_REQUESTED** [review]
Please, add comments in both places explaining why we changed direction (from inputs to outputs).
Otherwise based on Roland and your comment fix seems fine.

**Review by vnkozlov — APPROVED** [review]

**Pull request closed without merging**
