### PR TITLE
8269558: fix of JDK-8252657 missed to update history at the end of JVM TI spec

### PR DESCRIPTION
**Pull request by sspitsyn**
The fix of:
   8252657 JVMTI agent is not unloaded when Agent_OnAttach is failed
did not update the JVM TI spec history at the end of document. 
This PR adds missed item to the JVM TI spec history.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269558](https://bugs.openjdk.java.net/browse/JDK-8269558): fix of JDK-8252657 missed to update history at the end of JVM TI spec

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to 7a5b9b3bc0b71765c57b682cea8df27a1c16c5d5
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - **Reviewer**) ⚠️ Review applies to 7a5b9b3bc0b71765c57b682cea8df27a1c16c5d5

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/233/head:pull/233` \
`$ git checkout pull/233`

Update a local copy of the PR: \
`$ git checkout pull/233` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/233/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 233`

View PR using the GUI difftool: \
`$ git pr show -t 233`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/233.diff">https://git.openjdk.java.net/jdk17/pull/233.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up. This looks like a trivial fix to me.

**Review by plummercj — APPROVED** [review]

**Comment by sspitsyn** [comment]
Dan and Chris, thank you for quick review!

**Pull request closed without merging**
