### PR TITLE
8266614: update manpage for -Xlog:async 

### PR DESCRIPTION
**Pull request by dholmes-ora**
Please review this update to the java manpage to describe the new -Xlog:async flag

There are two places where the text is changed:

1. At the start where the -Xlog synopsis is given it now shows that `-Xlog:directive` is an allowed form where directive can be one of: help, disable, async
2.  A new subsection "-Xlog Output Mode" that explains async mode

The commited file is the java.1 nroff version which is not very readable, so I've included a commit that also contains a html version with the changed text flagged by "START NEW TEXT" and "END NEW TEXT". You can view that in rendered html via this link:

https://htmlpreview.github.io/?https://github.com/openjdk/jdk17/blob/8dcf544dfd2e19a3a49cce98d2d9abd9d2756538/java.html

Note that because the nroff file has not been updated for a while it also contains changes unrelated to this PR, the source changes for which have already been reviewed and approved. So just ignore those bits and look at the html file.

Thanks,
David

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266614](https://bugs.openjdk.java.net/browse/JDK-8266614): update manpage for -Xlog:async

### Reviewers
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)
 * [Xin Liu](https://openjdk.java.net/census#xliu) (@navyxliu - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/16/head:pull/16` \
`$ git checkout pull/16`

Update a local copy of the PR: \
`$ git checkout pull/16` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/16/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16`

View PR using the GUI difftool: \
`$ git pr show -t 16`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/16.diff">https://git.openjdk.java.net/jdk17/pull/16.diff</a>

</details>

### CODE REVIEW

**Comment by hseigel** [comment]
The changes look good!  Here's some optional suggestions.

Under the "Description" heading where it says "The following provides quick reference to the -Xlog command and syntax for options:", perhaps add something about -Xlog:async?

Possible rewording suggestions:

1. Change "The default value should be big enough to cater for most cases." to
          "The default value should be big enough to handle most cases."

2. Change "... trade memory overhead for log accuracy if they need to."
   to   "... trade memory overhead for log accuracy if needed."

**Review by hseigel — APPROVED** [review]
Thanks for doing this!
Harold

**Comment by dholmes-ora** [comment]
@navyxliu could you review this please.

Thanks,
David

**Comment by navyxliu** [comment]
Thanks for updating the manage. 
LGTM.

**Review by navyxliu — APPROVED** [review]

**Pull request closed without merging**
