### PR TITLE
8269064: Dropped messages of AsyncLogWriter cause memleak

### PR DESCRIPTION
**Pull request by navyxliu**
This patch freed c-strs for the dropped messages. Those c-strs are allocated from os::strdup.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269064](https://bugs.openjdk.java.net/browse/JDK-8269064): Dropped messages of AsyncLogWriter cause memleak

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Volker Simonis](https://openjdk.java.net/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/121/head:pull/121` \
`$ git checkout pull/121`

Update a local copy of the PR: \
`$ git checkout pull/121` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/121/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 121`

View PR using the GUI difftool: \
`$ git pr show -t 121`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/121.diff">https://git.openjdk.java.net/jdk17/pull/121.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Hi Xin,

This fix looks good and trivial.

Thanks for splitting the two issues.

David

**Review by simonis — APPROVED** [review]
Looks good to me.

Thanks for fixing,
Volker

**Pull request closed without merging**
