### PR TITLE
8268525: Some new memory leak after JDK-8248268 and JDK-8255557

### PR DESCRIPTION
**Pull request by wangweij**
Remove newly leaked memory.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268525](https://bugs.openjdk.java.net/browse/JDK-8268525): Some new memory leak after JDK-8248268 and JDK-8255557

### Reviewers
 * [Valerie Peng](https://openjdk.java.net/census#valeriep) (@valeriepeng - **Reviewer**)
 * [Anthony Scarpino](https://openjdk.java.net/census#ascarpino) (@ascarpino - **Reviewer**) ⚠️ Review applies to 923756084d248edcaab80790f9133c7a52ca299c

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/3/head:pull/3` \
`$ git checkout pull/3`

Update a local copy of the PR: \
`$ git checkout pull/3` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/3/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3`

View PR using the GUI difftool: \
`$ git pr show -t 3`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/3.diff">https://git.openjdk.java.net/jdk17/pull/3.diff</a>

</details>

### CODE REVIEW

**Comment by valeriepeng** [comment]
Changes look good to me. Thanks for catching these.
Valerie

**Review by valeriepeng — APPROVED** [review]

**Review by ascarpino — APPROVED** [review]
They look fine

**Review by valeriepeng — APPROVED** [review]
Update looks good.

**Pull request closed without merging**
