### PR TITLE
8266889: [macosx-aarch64] Crash with SIGBUS in MarkActivationClosure::do_code_blob during vmTestbase/nsk/jvmti/.../bi04t002 test run

### PR DESCRIPTION
**Pull request by AntonKozlov**
The change adds W^X transition in RawMonitor family of functions, fixing the crash. RawMonitor functions are treated specially, so W^X transition is not inserted automatically. A better fix would be in .xml description for entries generation, but for now it is too risky. I hope to get this fixed in 17 in the simplest way and do re-work in the 18. This change is still 100% correct for the reported bug.

Verified by: 
```
jtreg -vmoption:-XX:+AssertWXAtThreadSync test/hotspot/jtreg/vmTestbase/nsk/jvmti/scenarios/bcinstr/BI04/bi04t002
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266889](https://bugs.openjdk.java.net/browse/JDK-8266889): [macosx-aarch64] Crash with SIGBUS in MarkActivationClosure::do_code_blob during vmTestbase/nsk/jvmti/.../bi04t002 test run

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/244/head:pull/244` \
`$ git checkout pull/244`

Update a local copy of the PR: \
`$ git checkout pull/244` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/244/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 244`

View PR using the GUI difftool: \
`$ git pr show -t 244`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/244.diff">https://git.openjdk.java.net/jdk17/pull/244.diff</a>

</details>

### CODE REVIEW

**Comment by sspitsyn** [comment]
Hi Anton,
At least, some comments would be nice to have explaining why the switches are needed there.
Thanks,
Serguei

**Review by dholmes-ora — COMMENTED** [review]
I can understand that raw_enter and raw_wait need this fix because they have the ThreadBlockInVM transition; but why do we need it for raw_exit and raw_notify when they do not change the thread state ??

**Comment by AntonKozlov** [comment]
@dholmes-ora I added the W^X into all RawMonitor functions since they clearly slipped from the common JVMTI entry with W^X management. It was just precaution. But I don't see any problem with handling only raw_enter and raw_wait, updated the patch.

Handling only subset of functions also simplifies the comment suggested by @sspitsyn. 

Thanks for the comments!

**Review by theRealAph — APPROVED** [review]
OK. We really need to have a think about how W^X should be handled: this temporal coupling is a code smell, and will be be a reliability problem until we do something better.

**Review by sspitsyn — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Seems fine to address current problem, but we need a much clearer, more systematic approach to handling this (and enabling others to easily understand when and why it is needed).

Thanks,
David

**Comment by AntonKozlov** [comment]
Thanks for the reviews.

It's my fault I have not explained how W^X is supposed to work. I still does not consider this as the smell, but since someone thinks so, it's my bad. I'm going to create a page on cr.openjdk.java.net that will be a memo of the current state.

**Pull request closed without merging**
