### PR TITLE
8256934: C2: assert(C->live_nodes() <= C->max_node_limit()) failed: Live Node limit exceeded limit

### PR DESCRIPTION
**Pull request by chhagedorn**
The algorithm in step 2 in partial peeling to move nodes from the peeled section down to the non-peeled section creates a huge number of clones in the testcase which results in a live node assertion failure. The problem can be traced back to an inefficiency in creating new clones in `PhaseIdealLoop::clone_for_use_outside_loop()` when the graph contains cycles/diamonds to be cloned (see [example](https://github.com/chhagedorn/jdk/blob/bb1757a31883d33594fd8b4bb375de5cfc6a32ed/src/hotspot/share/opto/loopopts.cpp#L3560-L3586) taken from an improved algorithm for JDK-8268744)

Where the current algorithm needs to create around 90000 clones for the failing testcase, an improved algorithm only needs around 140 clones. However, for JDK 17, I propose to go with a simple bailout fix to minimize the risk (given that this is an edge case) and then follow up with an improved algorithm in an RFE ([JDK-8268744](https://bugs.openjdk.java.net/browse/JDK-8268744?filter=39569)).

Thanks,
Christian

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8256934](https://bugs.openjdk.java.net/browse/JDK-8256934): C2: assert(C->live_nodes() <= C->max_node_limit()) failed: Live Node limit exceeded limit

### Reviewers
 * [Roland Westrelin](https://openjdk.java.net/census#roland) (@rwestrel - **Reviewer**)
 * [Vladimir Ivanov](https://openjdk.java.net/census#vlivanov) (@iwanowww - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/54/head:pull/54` \
`$ git checkout pull/54`

Update a local copy of the PR: \
`$ git checkout pull/54` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/54/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 54`

View PR using the GUI difftool: \
`$ git pr show -t 54`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/54.diff">https://git.openjdk.java.net/jdk17/pull/54.diff</a>

</details>

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by chhagedorn** [comment]
Thanks Roland for your review!

**Review by iwanowww — APPROVED** [review]
Looks good.

**Comment by chhagedorn** [comment]
Thanks Vladimir for your review!

**Pull request closed without merging**
