### PR TITLE
8271160: runtime/jni/checked/TestCheckedJniExceptionCheck.java doesn't set -Djava.library.path

### PR DESCRIPTION
**Pull request by iignatev**
Hi all,

could you please review this small patch that sets `-Djava.library.path` to ` test.nativepath` for `TestCheckedJniExceptionCheck`'s child JVM so it will be able to locate the library?

from JBS:
> TestCheckedJniExceptionCheck spawns a child JVM that uses a test native library, TestCheckedJniExceptionCheck, but it doesn't add/set test.nativepath value to -Djava.library.path, so the child JVM can't find the library and fails. 
>
> this issue hasn't been noticed early b/c TestCheckedJniExceptionCheck doesn't check the exit code of the child JVM.

Thanks,
-- Igor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271160](https://bugs.openjdk.java.net/browse/JDK-8271160): runtime/jni/checked/TestCheckedJniExceptionCheck.java doesn't set -Djava.library.path

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to ff88410357805d16bd713ecadd3154ebb3342e21
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/273/head:pull/273` \
`$ git checkout pull/273`

Update a local copy of the PR: \
`$ git checkout pull/273` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/273/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 273`

View PR using the GUI difftool: \
`$ git pr show -t 273`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/273.diff">https://git.openjdk.java.net/jdk17/pull/273.diff</a>

</details>

### CODE REVIEW

**Review by dcubed-ojdk — APPROVED** [review]
Thumbs up on the changes.

What kind of testing has been done? I don't see any testing details in the PR.

**Comment by iignatev** [comment]
Thanks, Dan.

as I usually do for similar changes, I just run the changed test on `{linux,windows,macos}-x64` in OOB configuration.

**Comment by dcubed-ojdk** [comment]
Thanks for the testing info!

**Review by dholmes-ora — APPROVED** [review]
I don't have any issues with the change, but I will point out that this is another case of being bitten by jtreg's differing behaviour in agent mode and non-agent mode. Default execution locally works perfectly fine because the default mode will also set LD_LIBRARY_PATH in the environment and so the child VM works correctly. Whereas the jtreg mode used in our CI testing doesn't.

I also don't think the lack of checking for a zero exit code would cause this to spuriously pass either as there is expected output that would not be found if the test failed with UnsatisfiedLinkException due to the native library.

Thanks,
David

**Comment by dholmes-ora** [comment]
No I am wrong - the test does spuriously pass if the library is not found. Interesting ...

**Comment by iignatev** [comment]
> I also don't think the lack of checking for a zero exit code would cause this to spuriously pass either as there is expected output that would not be found if the test failed with UnsatisfiedLinkException due to the native library.


Hi David,

the lack of checking is exactly how I found this issue. the test passed as it skipped all its checks in `checkOuputForCorrectWarnings` b/c it didn't meet "TEST STARTED" line. I guess we can improve  `checkOuputForCorrectWarnings` to be more rigid in its check.

Thanks,
-- Igor

**Comment by dholmes-ora** [comment]
Right - I was just looking at that. The test should fail if the start line is not found.

**Review by dholmes-ora — APPROVED** [review]
Update looks good.

Thanks,
David

**Comment by iignatev** [comment]
Thanks, David.

/integrate

**Pull request closed without merging**
