### PR TITLE
8271412: ProblemList javax/sound/midi/Sequencer/Looping.java

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8271412](https://bugs.openjdk.java.net/browse/JDK-8271412): ProblemList javax/sound/midi/Sequencer/Looping.java
 * [JDK-8271413](https://bugs.openjdk.java.net/browse/JDK-8271413): ProblemList 2 locale tests on macOS-x64

### Reviewers
 * [Naoto Sato](https://openjdk.java.net/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/291/head:pull/291` \
`$ git checkout pull/291`

Update a local copy of the PR: \
`$ git checkout pull/291` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/291/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 291`

View PR using the GUI difftool: \
`$ git pr show -t 291`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/291.diff">https://git.openjdk.java.net/jdk17/pull/291.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@naotoj - Thanks for the fast review!

**Pull request closed without merging**
