### PR TITLE
8269830: SA's vm object vtable matching code sometimes matches on incorrect type

### PR DESCRIPTION
**Pull request by plummercj**
See the CR for details. This issue is causing a lot of failures related to some threads occasionally not being included in the jstack output, such as SteadyStateThread, Common-Cleaner, and "Signal Dispatcher". The bug caused SA to sometimes think a JavaThread object is actually an instance of the CompilerThread subclass, even though it is not. This results in jstack not including the thread in the output since it purposefully omits CompilerThreads.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269830](https://bugs.openjdk.java.net/browse/JDK-8269830): SA's vm object vtable matching code sometimes matches on incorrect type

### Reviewers
 * [Kevin Walls](https://openjdk.java.net/census#kevinw) (@kevinjwalls - Committer)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/206/head:pull/206` \
`$ git checkout pull/206`

Update a local copy of the PR: \
`$ git checkout pull/206` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/206/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 206`

View PR using the GUI difftool: \
`$ git pr show -t 206`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/206.diff">https://git.openjdk.java.net/jdk17/pull/206.diff</a>

</details>

### CODE REVIEW

**Review by kevinjwalls — APPROVED** [review]
Much simpler!

**Comment by plummercj** [comment]
> Much simpler!

Thank you Kevin!

Can I get one more review please?

**Review by sspitsyn — APPROVED** [review]
Nice cleanup.
Thanks,
Serguei

**Comment by plummercj** [comment]
Thanks Serguei!

**Pull request closed without merging**
