### PR TITLE
8269825: [TESTBUG] Missing testing for x86 KNL platforms

### PR DESCRIPTION
**Pull request by vnkozlov**
Knights family of X86 Intel CPU (KNL) does not support some of avx512 features (AVX512VL/BW) and have other restrictions. We may not have such kind of machines in our testing environment and may miss bugs as JBS history shows (look recent fixes for KNL).
On other hand we have some Windows VM instances which seem emulate KNL configuration and limit avx512 instructions on CPU which supports full set. Recent bug JDK-8269775 shows such example.
I suggest to add -XX:+UseKNLSetting x86 diagnostic flag to emulate KNL settings in HotSpot VM to test such configuration.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269825](https://bugs.openjdk.java.net/browse/JDK-8269825): [TESTBUG] Missing testing for x86 KNL platforms

### Reviewers
 * [Dean Long](https://openjdk.java.net/census#dlong) (@dean-long - **Reviewer**) ⚠️ Review applies to 9466fb97c61dccd49212119ad9d87c6b32939c7c
 * jbhateja - Committer ⚠️ Added manually

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17 pull/205/head:pull/205` \
`$ git checkout pull/205`

Update a local copy of the PR: \
`$ git checkout pull/205` \
`$ git pull https://git.openjdk.java.net/jdk17 pull/205/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 205`

View PR using the GUI difftool: \
`$ git pr show -t 205`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17/pull/205.diff">https://git.openjdk.java.net/jdk17/pull/205.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — APPROVED** [review]

**Comment by vnkozlov** [comment]
Thank you, Dean.

**Comment by jatin-bhateja** [comment]
Hi @dean-long , @vnkozlov ,
Since the idea is to test KNL settings on any latest X86 Server platform we should also turn off following options.
 if (is_intel()) { // Intel cpus specific settings
    if (is_knights_family()) {
      _features &= ~CPU_VZEROUPPER;
      _features &= ~CPU_AVX512BW;
      _features &= ~CPU_AVX512VL;
+      _features &= ~CPU_AVX512DQ;
+      _features &= ~CPU_AVX512_VNNI;
+      _features &= ~CPU_AVX512_VAES;
+      _features &= ~CPU_AVX512_VPOPCNTDQ;
+      _features &= ~CPU_AVX512_VPCLMULQDQ;
+      _features &= ~CPU_AVX512_VBMI;
+      _features &= ~CPU_AVX512_VBMI2;
    }
  }

**Comment by vnkozlov** [comment]
Thank you, @jatin-bhateja
I think I should be more clear here. What I want to emulate is VM instance we use in our seeting:
```
KVM virtualization detected

CPU: total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 85 stepping 4 microcode 0x1, cx8, cmov, fxsr, ht, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, lzcnt, tsc, avx, avx2, aes, erms, clmul, bmi1, bmi2, rtm, adx, avx512f, avx512dq, avx512cd, fma, clflush, clflushopt, clwb, hv
```

And because current KNL flags setting is matching it I used it. I don't want to emulate exactly KNL CPU.

**Comment by vnkozlov** [comment]
Tests listed in [8269828](https://bugs.openjdk.java.net/browse/JDK-8269828) passed with additional KNL CPU features switched off as @jatin-bhateja suggested. But it does not solve our internal testing issue.

I will change bug's subject and flag name to be specific that it is VM emulation instead of KNL CPU.

**Comment by jatin-bhateja** [comment]
Hi @vnkozlov , 
Thanks for clarifications, configuration of  VM guest mentions AVX512DQ feature which is not supported by KNL.
Below is the KNL features list generated using Intel's SDE (SW Dev Emulator).

```

SPROMPT>sde -knl -- cpuid -1 | grep "AVX512" | grep "true"
      AVX512F: AVX-512 foundation instructions = true
      AVX512PF: prefetch instructions          = true
      AVX512ER: exponent & reciprocal instrs   = true
      AVX512CD: conflict detection instrs      = true
SPROMPT>sde -knl -- cpuid -1 | grep "AVX512" | grep "false"
      AVX512DQ: double & quadword instructions = false
      AVX512IFMA: fused multiply add           = false
      AVX512BW: byte & word instructions       = false
      AVX512VL: vector length                  = false
      AVX512VBMI: vector byte manipulation     = false
      AVX512_VBMI2: byte VPCOMPRESS, VPEXPAND  = false
      AVX512_VNNI: neural network instructions = false
      AVX512_BITALG: bit count/shiffle         = false
      AVX512: VPOPCNTDQ instruction            = false
      AVX512_4VNNIW: neural network instrs     = false
      AVX512_4FMAPS: multiply acc single prec  = false
      AVX512_VP2INTERSECT: intersect mask regs = false
```

Regards

**Comment by vnkozlov** [comment]
Interesting. Excluding AVX512DQ does help to pass tests from 8269828 (at least on my local machine).

Yes, my listed before CPUID was incorrect (was generated with my patch). Here is correct one from one of crashes we see (no AVX512BW, AVX512VL, AVX512DQ, CLWB, FLUSHOPT):

```
CPU: total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 85 stepping 4 microcode 0x1, cx8, cmov, fxsr, ht, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, lzcnt, tsc, avx, avx2, aes, erms, clmul, bmi1, bmi2, rtm, adx, avx512f, avx512cd, fma, vzeroupper, clflush, hv
```

I am currently testing update for this PR which excludes AVX512DQ too.

**Comment by vnkozlov** [comment]
@jatin-bhateja 
What is your suggestion for this change? Because of my mistake about AVX512DQ I think I can just apply your additional features exclusion for KNL cpu and it will emulate VM settings we have. And I don't need separate settings for virtualization.

**Comment by jatin-bhateja** [comment]
> @jatin-bhateja
> What is your suggestion for this change? Because of my mistake about AVX512DQ I think I can just apply your additional features exclusion for KNL cpu and it will emulate VM settings we have. And I don't need separate settings for virtualization.

I agree with your suggestion. Settings enabled under UseNewCode with additional new features disabled for KNL will help in testing.

**Comment by vnkozlov** [comment]
The update changes were suggested by Jatin.

**Pull request closed without merging**
